---

- name: Add elixir plugin to asdf
  command: "$HOME/.asdf/bin/asdf plugin-add elixir"
  register: elixir_add
  failed_when: elixir_add == 1

- name: Install elixir versions
  command: "$HOME/.asdf/bin/asdf install elixir {{ item }}"
  loop: "{{ elixir_versions}}"

- name: "Set global version for elixir to {{ elixir_versions[0] }}"
  command: "$HOME/.asdf/bin/asdf global elixir {{ elixir_versions[0] }}" 
