---
- name: Set up local workstation
  hosts: local
  roles:
    # Tools 

    - role: xcode
      tags: 
        - xcode

    - role: bash
      tags: 
        - bash

    - role: homebrew
      tags:
        - homebrew

    - role: git
      tags:
        - git

    # Editor
    - role: alacritty
      tags: 
        - alacritty
        
    - role: vim
      tags:
        - vim

    - role: tmux
      tags:
        - tmux

    # Languages
        
    - role: asdf
      tags:
        - asdf

    - role: erlang
      tags:
        - erlang

    - role: elixir
      tags:
        - elixir

    - role: lua
      tags:
        - lua

    - role: fennel
      tags: 
        - fennel

    - role: rust
      tags: 
        - rust
