---

- name: Add erlang plugin to asdf
  command: "${HOME}/.asdf/bin/asdf plugin-add erlang"
  register: erlang_add
  failed_when: erlang_add == 1

- name: "Get openSSL"
  command: "brew --prefix openssl"
  register: openssl_path

- name: "Install erlang versions"
  command: "${HOME}/.asdf/bin/asdf install erlang {{ item }}"
  vars:
  environment: 
    - KERL_CONFIGURE_OPTIONS: "--without-javac --with-ssl={{ openssl_path }}"
  loop: "{{ versions }}"

- name: Set global version for erlang to {{versions[0]}}
  command: "asdf global erlang {{versions[0]}}" 
