---
- name: Establish vscode directory name
  set_fact:
    vscode_dir: $HOME/Library/Application\ Support/Code/User

- name: Check if VSCode settings exists
  stat:
    path: "{{ vscode_dir }}/settings.json"
  register: settings_check

- name: Backup settings.json
  command: "mv {{ vscode_dir }}/settings.json {{ vscode_dir }}/settings.json.bak"
  args:
    creates: "{{ vscode_dir }}/settings.json.bak"
  when: settings_check.stat.exists

- name: Symlink settings.json
  file:
    src: "{{ role_path }}/files/settings.json"
    dest: "$HOME/Library/Application Support/Code/User/settings.json"
    state: link
    force: yes

- name: Check if VSCode keybindings exists
  stat:
    path: "{{ vscode_dir }}keybindings.json"
  register: keybindings_check

- name: Backup keybindings.json
  command: "mv $HOME/Library/Application Support/Code/User/keybindings.json {{ vscode_dir }}/keybindings.json.bak"
  args:
    creates: "{{ vscode_dir }}/keybindings.json.bak"
  when: keybindings_check.stat.exists

- name: Symlink keybindings.json
  file:
    src: "{{ role_path }}/files/keybindings.json"
    dest: "$HOME/Library/Application Support/Code/User/keybindings.json"
    state: link
    force: yes

- name: Install Settings Sync Extension
  command: "code --install-extension Shan.code-settings-sync"
