---

# Add an icon to the Dock.

# NOTE: You'll need to define all these variables when including this file:
#           * name: Name of the application or directory



- name: Determine if {{ name }} is already in the Dock
  command: dockutil --find '{{ name }}'
  register: dock_icon
  ignore_errors: true 
  changed_when: false 

- name: Remove {{ name }} icon to the Dock
  command: dockutil --remove '{{ name }}' 
  when: dock_icon.rc == 0
  notify:
    - restart Dock
