---
- name: Check if compiler is installed. 
  stat:
    path: /usr/local/bin/elm
  register: elm_check

# TODO: ensure elm is expected version, like go.

- name: Download elm compiler
  get_url:
    url: "https://github.com/elm/compiler/releases/download/{{ elm_version }}/binary-for-mac-64-bit.gz"
    dest: /tmp/elm.gz
    force: yes
    mode: 0755
  when: elm_check.stat.exists == False
  register: fetch_elm


- name: Uncompress elm compiler
  command: "gunzip /tmp/elm.gz"
  args:
    creates: "/tmp.elm" 
  when: 
    - fetch_elm | bool 
    - fetch_elm.status_code == 200

- name: Move elm to path
  command: "mv /tmp/elm /usr/local/bin/elm"
  when: elm_check.stat.exists == False 
