---

- name: Ensure Homebrew is Installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Fail if Homebrew is not installed and install_homebrew_if_missing is false
  fail:
    msg: Homebrew is missing...Install from http://brew.sh/
  when:
    - not homebrew_check.stat.exists
    - not "{{ install_homebrew_if_missing }}"

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when:
    - not homebrew_check.stat.exists
    - "{{ install_homebrew_if_missing }}"

- name: Updating Homeerew
  homebrew:
    update_homebrew: true
  when: 
    - homebrew_check.stat.exists
    - "{{ update_homebrew_packages }}"

- name: Link brewfile 
  file:
    src: "{{ dotfiles_home }}/roles/homebrew/files/brewfile.link"
    dest: "{{ dotfiles_user_home }}/Brewfile"
    state: link
    force: yes

- name: Install from Brewfile.
  command: "brew bundle chdir={{ dotfiles_user_home }}"
  when: "{{ install_bundle }}" 

- name: See if OpenSSL library is linked
  shell: brew doctor 2>&1 | sed -ne '/You may wish to `brew unlink` these brews:/,$p' | grep openssl
  register: openssl_linked
  ignore_errors: TRUE
  changed_when: FALSE
  when: ansible_distribution == 'MacOSX' and ansible_distribution_version.startswith('10.11')

- name: For linking of OpenSSL library and headers on El Capitan
  homebrew:
    name: openssl
    state: linked
    install_options: force
  when: ansible_distribution == 'MacOSX' and ansible_distribution_version.startswith('10.11') and openssl_linked.rc != 0
