---

- name: Ensure Homebrew is Installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not homebrew_check.stat.exists

- name: Updating Homebrew
  command: "brew update"
  when: 
    - homebrew_check.stat.exists
    - upgrade_homebrew_packages

- name: Link brewfile 
  file:
    src: "{{ role_path }}/files/brewfile.link"
    dest: "$HOME/Brewfile"
    state: link
    force: yes

- name: Install from Brewfile.
  command: "brew bundle chdir=$HOME"
  when: install_bundle

- name: See if OpenSSL library is linked
  shell: brew doctor 2>&1 | sed -ne '/You may wish to `brew unlink` these brews:/,$p' | grep openssl
  register: openssl_linked
  ignore_errors: True
  changed_when: False 
  when: ansible_distribution == 'MacOSX' and ansible_distribution_version.startswith('10.11')

- name: For linking of OpenSSL library and headers on El Capitan
  homebrew:
    name: openssl
    state: linked
    install_options: force
  when: ansible_distribution == 'MacOSX' and ansible_distribution_version.startswith('10.11') and openssl_linked.rc != 0
