---

# I touch the trackpad way too often for this to be enabled
- name: Disable tap-to-click
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    value: 0
    type: int

- name: Disable tap-to-click for Bluetooth trackpad
  osx_defaults:
    domain: "{{ item }}"
    key: Clicking
    value: 0
    type: int
  with_items:
    - com.apple.driver.AppleBluetoothMultitouch.trackpad
    - com.apple.AppleMultitouchTrackpad

- name: Disable tap-to-click for login screen
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    value: 0
    type: int


# Enable 3-finger drag. (Moving with 3 fingers in any window "chrome" moves the window.)
- name: Enable 3-finger drag
  osx_defaults:
    domain: "{{ item }}"
    key: TrackpadThreeFingerDrag
    value: true
    type: bool
  with_items:
    - com.apple.driver.AppleBluetoothMultitouch.trackpad
    - com.apple.AppleMultitouchTrackpad

# Enable scroll-to-zoom with Ctrl (^) modifier key (and 2 fingers).
- name: Enable scroll-to-zoom
  osx_defaults:
    domain: com.apple.universalaccess
    key: closeViewScrollWheelToggle
    value: true
    type: bool

- name: Enable scroll-to-zoom when Control key is held down
  osx_defaults:
    domain: "{{ item }}"
    key: HIDScrollZoomModifierMask
    value: 262144
    type: int
  with_items:
    - com.apple.driver.AppleBluetoothMultitouch.trackpad
    - com.apple.AppleMultitouchTrackpad
